### ISSUE TITLE
Unicode

### ISSUE THREAD

**Issue by neimanpinchas** [apmckinlay/csuneido#8]
What is possible to do to use suneido with unicode characters?

**Comment by apmckinlay** [comment]
Sorry, Suneido is only designed for 8 bit characters. You could store UTF-8 in strings, but there is very little support for doing anything with it.

**Comment by neimanpinchas** [comment]
Hi

I almost gave up from using suneido

One green day i looked back into it and i came up with a solution

 - Changed the Support for non-unicode programs setting in windows to "Hebrew"
 - Changed the font from segoe UI to another that contains the glyphs (Consolas in my case)

Than i was able to use Hebrew in forms as well as in the database, the only problem is that i cannot move the suneido file to another computer, thats OK for me.

I am wondering if its possible to update the default font for the whole system, including the workspace and library view.

**Comment by apmckinlay** [comment]
Nice! Glad you found a solution.

The standard fonts are specified in StdFonts in stdlib. There are probably a few places that do not use StdFonts but it should handle most things.
